---
# - name: Configure jenkins
#   hosts: jenkins
#   roles:
#     - java_installation
#     - set_jenkins

- name: Configure tomcat
  hosts: tomcat
  roles:
    # - java_installation
    - set_tomcat

